services:
  rag:
    image: ucsm-rag
    container_name: ucsm-rag
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.rag
    restart: unless-stopped

  ui:
    image: ucsm-ui
    container_name: ucsm-ui
    build:
      context: .
      dockerfile: Dockerfile.ui
    depends_on:
      - rag
    restart: unless-stopped
