version: "3.9"

services:
  rag:
    image: ucsm-rag
    container_name: ucsm-rag
    build:
      context: .
      dockerfile: docker/Dockerfile.rag
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./db:/app/db
    restart: unless-stopped

  ui:
    build:
      context: .
      dockerfile: docker/Dockerfile.ui
    image: ucsm-ui
    container_name: ucsm-ui
    depends_on:
      - rag
    ports:
      - "8501:8501"
